---
# Mybatis Flex的配置 https://mybatis-flex.com/zh/base/configuration.html
mybatis-flex:
  global-config:
    print-banner: false
spring:
  # 数据库的相关配置
  datasource:
    url: jdbc:postgresql://192.168.1.10:32297/lx_ateng?currentSchema=public&stringtype=unspecified  # 数据库连接URL
    username: postgres  # 数据库用户名
    password: Lingo@local_postgresql_5432  # 数据库密码
    driver-class-name: org.postgresql.Driver  # PostgreSQL数据库驱动类
    # driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL数据库驱动类
    type: com.alibaba.druid.pool.DruidDataSource  # 使用Druid数据源
    # Druid连接池配置 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      initial-size: 10  # 初始化连接池大小
      min-idle: 10  # 最小空闲连接数
      max-active: 100  # 最大活跃连接数
      max-wait: 10000  # 获取连接的最大等待时间，单位毫秒
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 30000
#      pool-name: HikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1