# 环境配置
spring:
  application:
    name: ${project.artifactId}
  profiles:
    active: @profiles.active@
    desc: @profiles.desc@
---
# ApiFox 设置 API 请求前缀
# https://apifox.com/help/applications-and-plugins/idea/setting/setting-rule#class-prefix-path
class.prefix.path: /system