apiVersion: apps/v1
kind: Deployment
metadata:
  name: ateng-modules-system
  namespace: ateng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ateng-modules-system
  template:
    metadata:
      labels:
        app: ateng-modules-system
    spec:
      hostname: ateng-modules-system
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: ateng-boot
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - name: ateng-modules-system
          image: registry.lingo.local/ateng/ateng-modules-system:latest
          imagePullPolicy: Always
          #resources:
          #  limits:
          #    cpu: '2'
          #    memory: 2Gi
          #  requests:
          #    cpu: 500m
          #    memory: 512Mi
          ports:
            - name: tcp-20522
              protocol: TCP
              containerPort: 20522
          env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx2048m"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 20522
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 20522
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "curl -u admin:Admin@123 -X POST http://localhost:20522/actuator/shutdown && sleep 25" ]
---
apiVersion: v1
kind: Service
metadata:
  name: ateng-modules-system
  namespace: ateng
  labels:
    app: ateng-modules-system
spec:
  type: ClusterIP
  selector:
    app: ateng-modules-system
  ports:
    - port: 20522
      targetPort: 20522
---
